### ISSUE TITLE
arg input doesn't work properly

### ISSUE THREAD

**Issue by AtomicSponge** [AtomicSponge/script-tray#1]
arg input doesn't work properly, fixing promise

**Comment by AtomicSponge** [comment]
gotta review async in JS :p

**Comment by wtfsystems** [comment]
fixed

**Comment by AtomicSponge** [comment]
gota update logic a bit more, need to make it step thru each arg THEN combine, almost done :p

**Comment by AtomicSponge** [comment]
bam!
